defmodule ElixirTestProject.Schemas.User do
  use Ecto.Schema
  # Primary key is a binary_id (UUID) autogenerated by Ecto
  @primary_key {:id, :binary_id, autogenerate: true}
  @derive {Phoenix.Param, key: :id}
  import Ecto.Changeset

  @type t :: %__MODULE__{
          id: Ecto.UUID.t() | nil,
          name: String.t() | nil,
          city: String.t() | nil,
          country: String.t() | nil,
          address: String.t() | nil,
          phone: String.t() | nil,
          phone_code: String.t() | nil,
          password: String.t() | nil,
          password_hash: String.t() | nil,
          is_seller: boolean(),
          online: boolean(),
          last_online_at: DateTime.t() | nil,
          avatar: String.t() | nil,
          coordinates: list(float()) | nil,
          location: map() | nil,
          inserted_at: NaiveDateTime.t() | nil,
          updated_at: NaiveDateTime.t() | nil
        }

  schema "users" do
    field :name, :string
    field :city, :string
    field :country, :string
    field :address, :string
    field :phone, :string
    field :phone_code, :string
    field :password, :string, virtual: true
    field :password_hash, :string
    field :is_seller, :boolean, default: false
    field :online, :boolean, default: false
    field :last_online_at, :utc_datetime
    field :avatar, :string
    field :coordinates, {:array, :float}, default: []
    field :location, :map, default: %{}

    timestamps()
  end

  def registration_changeset(user, attrs) do
    user
    |> cast(attrs, [:name, :phone, :phone_code, :password])
    |> validate_required([:name, :phone, :phone_code, :password])
    |> validate_length(:password, min: 10)
    |> unique_constraint(:phone)
    |> put_password_hash()
  end

  def status_changeset(user, attrs) do
    # Ensure last_online_at is always set when online = true
    attrs =
      if attrs[:online] || attrs["online"],
        do: Map.put(attrs, :last_online_at, DateTime.utc_now()),
        else: attrs

    user
    |> cast(attrs, [:online, :last_online_at])
    |> validate_required([:online, :last_online_at])
  end

  @doc """
  Changeset used when updating editable profile fields from the frontend.
  Only allows a whitelisted set of attributes and enforces basic length limits.
  """
  def profile_changeset(user, attrs) do
    user
    |> cast(attrs, [:name, :city, :country, :coordinates, :location, :avatar])
    |> validate_length(:name, min: 1, max: 120)
    |> validate_length(:city, max: 120)
    |> validate_length(:country, max: 120)
    |> validate_length(:avatar, max: 1000)
    |> validate_coordinates()
  end

  defp validate_coordinates(changeset) do
    case get_change(changeset, :coordinates) do
      nil ->
        changeset

      coords when is_list(coords) and length(coords) == 2 ->
        if Enum.all?(coords, &is_float/1),
          do: changeset,
          else: add_error(changeset, :coordinates, "must be an array of 2 floats")

      _ ->
        add_error(changeset, :coordinates, "must be an array of 2 floats")
    end
  end

  defp put_password_hash(changeset) do
    case changeset do
      %Ecto.Changeset{valid?: true, changes: %{password: password}} ->
        put_change(changeset, :password_hash, Pbkdf2.hash_pwd_salt(password))

      _ ->
        changeset
    end
  end
end
