defmodule ElixirTestProject.Schemas.User do
  use Ecto.Schema
  # Primary key is a binary_id (UUID) autogenerated by Ecto
  @primary_key {:id, :binary_id, autogenerate: true}
  @derive {Phoenix.Param, key: :id}
  import Ecto.Changeset

  schema "users" do
    field :name, :string
    field :phone, :string
    field :phone_code, :string
    field :password, :string, virtual: true
    field :password_hash, :string
    field :is_seller, :boolean, default: false

    timestamps()
  end

  def registration_changeset(user, attrs) do
    user
    |> cast(attrs, [:name, :phone, :phone_code, :password])
    |> validate_required([:name, :phone, :phone_code, :password])
    |> validate_length(:password, min: 10)
    |> unique_constraint(:phone)
    |> put_password_hash()
  end

  defp put_password_hash(changeset) do
    case changeset do
      %Ecto.Changeset{valid?: true, changes: %{password: password}} ->
        put_change(changeset, :password_hash, Pbkdf2.hash_pwd_salt(password))

      _ ->
        changeset
    end
  end
end
